### ISSUE TITLE
Install with homebrew & other package management systems

### ISSUE THREAD

**Issue by mgwidmann** [sup/meld#6]

**Comment by sup** [comment]
@mgwidmann does homebrew accept executable scripts as formulas or only compiled binaries? if so, i'll get on it

**Comment by sup** [comment]
just checked, the official repo doesn't like non-popular or self-authored stuff. probably gonna make my own tap

**Comment by mgwidmann** [comment]
:+1:

**Comment by sup** [comment]
done! you can do:
```
brew tap stuffs/tap
brew install meld
```
now! i'll edit the readme right away

**Comment by mgwidmann** [comment]
:+1:
